coverage:
# Remember to change values in build.gradle.kts too
  ignore:
  - **/*Event.kt
  - **/*State.kt
  - **/*Configuration.kt
  - **/*Runner.kt
  - **/generated/*
  status:
    project: off
    patch: off